version: '3'
services:
  flask:
    build: ./LiberalPython
    container_name: app-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True    
      - PYTHONDONTWRITEBYTECODE=1
    restart: on-failure
    volumes:
      - ./data:/backend
      - ./LiberalPython/LiberalPython/content/outputs/checkpoint-32070-epoch-15:/content/outputs/checkpoint-32070-epoch-15
    ports:
      - "80:5000"
    command: python runserver.py